# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008e44fb2b382529fe7a7aebd82a7106f5b5b8792dd4a5340c5f40cd12180ab57137205fb04d636b1682b96449ef94bd31f09bb5383d71c6caae8d3f18295102

test:
  secret_key_base: a0374997cba1088c463f8ecc6883e8e0505fd4023469d193c7d36d361d55fcc259754736bc482ca6c08eb63f176ffc480d9ec5523fa5d85d4f162370e7927e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
